name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: BackEnd - Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: BackEnd - Restore dependencies
        working-directory: backend
        run: dotnet restore

      - name: BackEnd - Build
        working-directory: backend
        run: dotnet build --no-restore

      - name: FrontEnd - Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: FrontEnd - Install Packages
        working-directory: frontend
        run: pnpm install

      - name: FrontEnd - Build Project
        working-directory: frontend
        run: pnpm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}