name: CI - Backend

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    path: 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        working-directory: backend
        run: dotnet restore

      - name: Build
        working-directory: backend
        run: dotnet build --no-restore
